name: Create Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Directory containing files to upload
        path: target/release/
